system:
 plant: chrono
 params:
  step_size: 0.005
  tire_step_size: 0.0025

 flags:
  system_shutdown: false
  initialized: true

 chrono:
  namespace: chrono
  flags:
   initialized: false
   running: false
   gui: true
  field:
   p: [0,190,-5]
   s: [10,400,100]
   pa: [-5,40,0]
   sa: [10,100,50] # height, length, width
   pb: [-5,140,0]
   sb: [10,100,50]
   pc: [-5,240,0]
   sc: [10,100,50]
   pd: [-5,340,0]
   sd: [10,100,50]

 planner: default
 default:
  flags:
   initialized: true
   goal_attained: false
