system:
 plant: chrono
 params:
  step_size: 0.005
  tire_step_size: 0.0025

 flags:
  system_shutdown: false
  initialized: true

 chrono:
  namespace: chrono
  flags:
   initialized: false
   running: false
   gui: true

  terrain:
   position: [0,190,-5]
   length: 100. # size in Chrono X direction
   width: 400.  # size in Chrono Y direction
   frictCoeff: 0.9
   restCoeff: 0.01

 planner: default
 default:
  flags:
   initialized: true
   goal_attained: false

case:
 actual:
  X0:
   x: 0.0
   yVal: 0.0
   z: 1.0
