system:
 plant: chrono
 params:
  step_size: 0.005
  tire_step_size: 0.0025

 flags:
  system_shutdown: false
  initialized: true

 chrono:
  namespace: chrono
  flags:
   initialized: false
   running: false
   gui: true
  field:
   pa: [0,40,0]
   sa: [5,100,50] # height, length, width
   pb: [0,140,0]
   sb: [5,100,50]
   pc: [0,240,0]
   sc: [5,100,50]
   pd: [0,340,0]
   sd: [5,100,50]

 planner: default
 default:
  flags:
   initialized: true
   goal_attained: false
