case:
 goal:
  x: 200.
  yVal: 125.
  psi: 1.5701
  tol: 4

 actual:
  X0:
   x: 200.0
   yVal: 0.0
   v: 0.0
   r: 0.0
   psi: 1.57079632679
   sa: 0.0
   ux: 0.0
   ax: 0.0
  obstacle:
   num: 1
   radius: [6.]
   length: [5.]
   x0: [200]
   y0: [110]
   vx: [0]
   vy: [0]
