/*Loucas includes*/
#include  <stdio.h>
#include  <ctype.h>
void read_parameters(int param_num, int state_num, char *input_file, XXDouble *x0);

/*Loucas variables*/
	char name[256],date[256],input[256];

	/*Loucas read parameters*/
	strcpy(name,"model - Version 3.0");
	strcpy(date, "Last updated August 30, 2002");
	strcpy(input,"model_parameters");
	printf(name);
	printf("\nCode generated by 20-sim ANSI-C Code Generator\n");
	printf("Enhacements by Dr. Loucas S. Louca\n");
	printf("Automated Modeling Laboratory\n");
	printf("The University of Michigan\n");
	printf(date);
	printf("\nReading data from: %s.dat\n\n", input);
	read_parameters(no_of_param, np_of_states, input, xx_s);
