macro F_YF() #(V, U, Ax, R, SA)		# front tire force
  code = quote
    if length(Ax) != 1
      Fyf = zeros(length(Ax),1)
      for ii in eachindex(Ax)
        Fyf[ii] = 278.2789450759981 + ((PD2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX))^2 )^(0.5)))+EP))*((atan((V[ii] + la*R[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)) - ((PE2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX) + PE1)*(1 - PE3)*(((atan((V[ii] + la*R[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX) + PH1))/((((atan((V[ii] + la*R[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)^2 )^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX))^2 )^(0.5)))+EP))*((atan((V[ii] + la*R[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX))))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)) + ((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)))/(((PD2*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX))^2 )^(0.5)))+EP))*((atan((V[ii] + la*R[ii])/(U[ii]+EP)) - SA[ii]) + PH2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)))))) + (PV2*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PV1*(FzF0 - (Ax[ii] - V[ii]*R[ii])*KZX)));
      end
    else
      Fyf = Float64
      Fyf = 278.2789450759981 + ((PD2*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*(FzF0 - (Ax - V*R)*KZX))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*R)*KZX))))/(((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX)) + ((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX)))/(((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX))^2 )^(0.5)))+EP))*((atan((V + la*R)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*R)*KZX) + PH1)) - ((PE2*(FzF0 - (Ax - V*R)*KZX) + PE1)*(1 - PE3)*(((atan((V + la*R)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*R)*KZX) + PH1))/((((atan((V + la*R)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*R)*KZX) + PH1)^2 )^(0.5)))*((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*R)*KZX))))/(((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX)) + ((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX)))/(((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX))^2 )^(0.5)))+EP))*((atan((V + la*R)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*R)*KZX) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzF0 - (Ax - V*R)*KZX))))/(((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX)) + ((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX)))/(((PD2*PC1*(FzF0 - (Ax - V*R)*KZX)^2 + PD1*PC1*(FzF0 - (Ax - V*R)*KZX))^2 )^(0.5)))+EP))*((atan((V + la*R)/(U+EP)) - SA) + PH2*(FzF0 - (Ax - V*R)*KZX) + PH1)))))) + (PV2*(FzF0 - (Ax - V*R)*KZX)^2 + PV1*(FzF0 - (Ax - V*R)*KZX)));
    end
    Fyf
  end
  return esc(code)
end
