macro F_YR()#(V, U, Ax, r, SA) # rear tire force
	code =quote
		if length(Ax) != 1
			Fyr = zeros(length(Ax),1)
			for ii in eachindex(Ax)
				Fyr[ii] = 259.95925391136984 + ((PD2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX))))/(((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)) + ((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)))/(((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX))^2)^(0.5)))+EP))*((atan((V[ii] - lb*R[ii])/(U[ii]+EP))) + PH2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)) - ((PE2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX) + PE1)*(1 - PE3*(((atan((V[ii] - lb*R[ii])/(U[ii]+EP))) + PH2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX) + PH1))/((((atan((V[ii] - lb*R[ii])/(U[ii]+EP))) + PH2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)^2 )^(0.5))))*((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX))))/(((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)) + ((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)))/(((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX))^2)^(0.5)))+EP))*((atan((V[ii] - lb*R[ii])/(U[ii]+EP))) + PH2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX))))/(((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)) + ((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)))/(((PD2*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PD1*PC1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX))^2)^(0.5)))+EP))*((atan((V[ii] - lb*R[ii])/(U[ii]+EP))) + PH2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX) + PH1)))))) + (PV2*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)^2 + PV1*(FzR0 + (Ax[ii] - V[ii]*R[ii])*KZX)));
			end
		else
			Fyr = Float64
			Fyr = 259.95925391136984 + ((PD2*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*(FzR0 + (Ax - V*R)*KZX))*sin(PC1*atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*R)*KZX))))/(((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX)) + ((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX)))/(((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX))^2)^(0.5)))+EP))*((atan((V - lb*R)/(U+EP))) + PH2*(FzR0 + (Ax - V*R)*KZX) + PH1)) - ((PE2*(FzR0 + (Ax - V*R)*KZX) + PE1)*(1 - PE3*(((atan((V - lb*R)/(U+EP))) + PH2*(FzR0 + (Ax - V*R)*KZX) + PH1))/((((atan((V - lb*R)/(U+EP))) + PH2*(FzR0 + (Ax - V*R)*KZX) + PH1)^2 )^(0.5))))*((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*R)*KZX))))/(((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX)) + ((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX)))/(((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX))^2)^(0.5)))+EP))*((atan((V - lb*R)/(U+EP))) + PH2*(FzR0 + (Ax - V*R)*KZX) + PH1)) - atan((((PK1*sin(2*atan(PK2*(FzR0 + (Ax - V*R)*KZX))))/(((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX)) + ((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX)))/(((PD2*PC1*(FzR0 + (Ax - V*R)*KZX)^2 + PD1*PC1*(FzR0 + (Ax - V*R)*KZX))^2)^(0.5)))+EP))*((atan((V - lb*R)/(U+EP))) + PH2*(FzR0 + (Ax - V*R)*KZX) + PH1)))))) + (PV2*(FzR0 + (Ax - V*R)*KZX)^2 + PV1*(FzR0 + (Ax - V*R)*KZX)));
		end
		Fyr
	end
	return esc(code)
end
