system:
 vehicle_description:
  flags:
   postion_update_external: false
   lidar_initialized: false
   obstacles_initialized: false
 nloptcontrol_planner:
  nameSpace: nloptcontrol
  flags:
   initilized: false
   known_environment: true
   3DOF_plant: true
   goal_attained: false
 initialized: false
 planner: nloptcontrol 
