system:

 params:
  step_size: 0.001
  simulation_time: 1.0

 flags:
  initialized: false
  paused: true

 shutdown:
  flags:
   running: true
   initialized: false
   shutdown: false
  params:
    shutdown_initiation_flags: ["system/flags/goal_attained", "/vehicle_collided"]
    shutdown_completion_flags: []

 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   obstacles_spawned: false
   postion_update_external: false
  params:
   step_distance: 0.0

 obstacle_detector:
  flags:
   running: true
   initialized: false
