system:
 planner: nloptcontrol_planner
 plant: chrono

 params:
  step_size: 0.005
  goal_tol: 0.1
  tire_step_size: 0.00025
  timelimit: 50

 flags:
  goal_attained: false
  rollover: false
  timelimit: false
  initialized: false
  paused: true

 result_store:
   flags:
     running: true
     initialized: false
     shutdown: false

 shutdown:
  flags:
   running: true
   initialized: false
   shutdown: false
  params:
    shutdown_initiation_flags: ["result_store/flags/shutdown"]
    shutdown_completion_flags: []

 nloptcontrol_planner:
  namespace: nloptcontrol_planner
  flags:
   running: true
   initialized: false
   known_environment: false

 chrono:
  namespace: chrono
  flags:
   initialized: false
   running: true
   gui: false
  field:
   h: 0
   l: 1000.0
   w: 1000.0

 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   obstacles_spawned: false
   postion_update_external: true

 obstacle_detector:
  flags:
   running: true
   initialized: false

 sim_time:
   flags:
    initialized: false
    running: true
