system:
 planner: nloptcontrol_planner
 plant: chrono

 params:
  step_size: 0.003
  goal_tol: 0.1
  tire_step_size: 0.00025
  timelimit: 50

 flags:
  not_optimal: false
  fall: false
  goal_attained: false
  rollover: false
  timelimit: false
  initialized: false
  paused: true
  done: false

 result_store:
   flags:
     running: true
     initialized: false
     shutdown: false

 shutdown:
  flags:
   running: true
   initialized: false
   shutdown: false
  params:
    shutdown_initiation_flags: ["result_store/flags/shutdown"]
    shutdown_completion_flags: []

 nloptcontrol_planner:
  namespace: nloptcontrol_planner
  flags:
   running: true
   initialized: false
   known_environment: false

 chrono:
  namespace: chrono
  flags:
   initialized: false
   running: true
   gui: false
  field:
   p: [0,190,-5]
   s: [100,400,10]
   pa: [0,0,40]
   sa: [10,75,15] # height,length, width
   pb: [0,0,140]
   sb: [10,75,100]
   pc: [0,0,240]
   sc: [10,75,100]
   pd: [0,0,340]
   sd: [10,75,100]

 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   obstacles_spawned: false
   postion_update_external: true

 obstacle_detector:
  flags:
   running: true
   initialized: false

 sim_time:
   flags:
    initialized: false
    running: true
