system:
 planner: nloptcontrol_planner
 plant: chrono

 params:
  step_size: 0.005
  goal_tol: 0.1
  tire_step_size: 0.00025

 flags:
  goal_attained: false
  initialized: false
  paused: true

 shutdown:
  flags:
   running: true
   initialized: false
  params:
    shutdown_initiation_flags: ["system/flags/goal_attained", "/vehicle_collided"]
    shutdown_completion_flags: []

 nloptcontrol_planner:
  namespace: nloptcontrol_planner
  flags:
   running: true
   initialized: false
   known_environment: true

 chrono:
  namespace: chrono
  flags:
   initialized: false
   running: true
   gui: true
  field:
   h: 0
   l: 500.0
   w: 500.0

 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   obstacles_spawned: false
   postion_update_external: true

 sim_time:
   flags:
    initialized: false
    running: true
