float64 texP                      # predicted execution horizon [s]
float64 texA                      # actual execution horizon [s]
float64 tSolve                    # optimization time [s]
string status                     # optimization status
float64[] X0p                     # predicted initial state vector
float64[] X0a                     # actual initial state vector
float64[] X0e                     # error in prediction of initial state vector
