<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="body" params="base_link *base_geometry">

    <!-- Base Footprint -->
    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
    <link name="base_footprint"/>

    <joint name="joint1" type="fixed" >
      <origin xyz="0 0 ${base_clearance}" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="${base_link}" />
    </joint>

    <!-- Base Link -->
    <!--Actual body/chassis of the robot-->
    <link name="${base_link}" >
      <visual>
        <xacro:if value="${mesh_mode == 1}">
          <origin xyz="0 0 ${-wheel_radius}" rpy="0 0 ${pi}" />
          <geometry>
            <mesh filename="package://vehicle_description/meshes/body.dae" scale=" ${scale_factor} ${scale_factor} ${scale_factor}"/>
          </geometry>
        </xacro:if>
        <xacro:if value="${mesh_mode == 0}">
          <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
          <xacro:insert_block name="base_geometry" />
        </xacro:if>
      </visual>
      <collision>
        <!--selfCollide>false</selfCollide-->
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        <xacro:insert_block name="base_geometry" />
      </collision>
      <inertial>
        <mass value="1500"/>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <inertia ixx="1000.0" ixy="0" ixz="0" iyy="1000.0" iyz="0" izz="1000.0"/>
      </inertial>
    </link>

    <!-- Link1 -->
    <gazebo reference="${base_link}">
      <!--material>Gazebo/Orange</material-->
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="${base_link}" >
      <sensor name="my_contact" type="contact">
        <plugin name="contact_sensor" filename="libcontact_sensor_mavs.so">
          <rosParamName>/vehicle_collided</rosParamName>
        </plugin>
        <contact>
            <!-- IMPORTANT: URDF to sdf parser creates name for the collision block by itself.
            See: http://answers.gazebosim.org/question/15095/gazebo-contact-sensor-added-to-a-robot-link-in-urdf-file-is-not-working-as-expected/
            and: http://answers.gazebosim.org/question/12687/problems-while-parsing-gazebo-urdf-elements-with-gazebo7-and-ros-jade/
            BE CAREFUL when renaming base_footprint link defined at top, it should be
            updated below as well-->
          <collision>base_footprint_fixed_joint_lump__${base_link}_collision</collision>
        </contact>
        <update_rate>5</update_rate>
      </sensor>
    </gazebo>


  </xacro:macro>

</robot>
