# parameters for both ThreeDOFv2 and KinematicBicycle
# KinematicBicycle parameters are a subset of ThreeDOFv2 parameters

# vehicle Limits
# x_min, x_max, y_min, y_max found in planner config file
sa_min: -0.5235983333333333 #  -30*3.14159/180
sa_max: 0.5235983333333333 #  30*3.14159/180
psi_min: -6.28318
psi_max: 6.28318
u_min: 0.01
u_max: 29.
ax_min: -2.
ax_max: 2.
sr_min: -0.0872663888888889  #-5*3.14159/180
sr_max: 0.0872663888888889   #5*3.14159/180
jx_min: -5.
jx_max: 5.

# define model parameters
la: 1.5775        # distance from CoG to front axle
lb: 1.7245        # distance from CoG to rear axle
m: 2.6887e+03
Izz: 4.1101e+03
FzF0: 1.3680e+04
FzR0: 1.2696e+04
KZX: 806.
KZYR: 1076.
KZYF: 675.

# defines polynominal for acceleration bounds
AXC: [-0.000128015180401862,0.00858618595422724,-0.225657108071454,3.08283259993589,-0.000138537090018958,0.00684702729623608,-0.120391102052425,-3.55886697370079]

# tire parameters
FZ0: 35000.0
PCY1: 1.5874               #Shape factor Cfy for lateral forces
PDY1: 0.73957              #Lateral friction Muy
PDY2: -0.075004            #Variation of friction Muy with load
PEY1: 0.37562              #Lateral curvature Efy at Fznom
PEY2: -0.069325            #Variation of curvature Efy with load
PEY3: 0.29168              #Zero order camber dependency of curvature Efy
PKY1: -10.289              #Maximum value of stiffness Kfy/Fznom
PKY2: 3.3343               #Load at which Kfy reaches maximum value
PHY1: 0.0056509            #Horizontal shift Shy at Fznom
PHY2: -0.0020257           #Variation of shift Shy with load
PVY1: 0.015216             #Vertical shift in Svy/Fz at Fznom
PVY2: -0.010365            #Variation of shift Svy/Fz with load

Caf: -8.4138e+4            # cornering stiffness--front axle (N/rad)
Car: -7.8126e+4            # cornering stiffness-- rear axle (N/rad)
Fy_min: -7500
Fy_max: 7500

# solver parameters
Fz_min: 1000.
Fz_off: 100.
# NOTE: a_t and b_t are calcuated in src/Three_DOF/parameters.jl in VehicleModels.jl
