goal:
 x: 200.
 yVal: 125.
 psi: 1.5701
 tol: 15.  # NOTE this is a bit redundant with the tolerance fx and fy

X0:
 x: 200.0
 yVal: 0.0
 v: 0.0
 r: 0.0
 psi: 1.57079632679
 sa: 0.0
 ux: 17.0
 ax: 0.0

obstacle:
 num: 4
 radius: [10.,2.,5.,3.]
 length: [5.,5.,5.]
 x0: [180,180,220,200]
 y0: [75,40,60,100]
 vx: [-3,4,-2,0]
 vy: [-2,4,2.5,0]
